objects:
  role: {}
plugins:
  become: {}
  cache: {}
  callback: {}
  cliconf: {}
  connection: {}
  httpapi: {}
  inventory:
    oneview:
      description: HPE OneView inventory source
      name: oneview
      version_added: 1.0.0
  lookup: {}
  module:
    ilo_boot_order:
      description: Manage boot order
      name: ilo_boot_order
      namespace: ''
      version_added: null
    ilo_power_state:
      description: Manage server power state via iLO
      name: ilo_power_state
      namespace: ''
      version_added: null
    ilo_security_settings:
      description: Manage iLO Security settings
      name: ilo_security_settings
      namespace: ''
      version_added: null
    ilo_smartstorage_raids:
      description: Create/configure/delete smartstorage raids
      name: ilo_smartstorage_raids
      namespace: ''
      version_added: null
    ilo_thermal_settings:
      description: Manage iLO Thermal settings
      name: ilo_thermal_settings
      namespace: ''
      version_added: null
    oneview_inventory:
      description: Generates the same information as the oneview_inventory plugin.
      name: oneview_inventory
      namespace: ''
      version_added: null
    oneview_racks_info:
      description: Content of /rest/racks endpoint of OneView
      name: oneview_racks_info
      namespace: ''
      version_added: null
    oneview_server_hardware_info:
      description: Content of /rest/server-hardware endpoint of OneView
      name: oneview_server_hardware_info
      namespace: ''
      version_added: null
  netconf: {}
  shell: {}
  strategy: {}
  vars: {}
version: 2.1.0
