---
name: Guard version tag
# When a release tag 'v*' is created, make sure that
# - RELEASE files contains the same version
# - galaxy.yml contains the same version
# - CHANGELOG.rst contains the same version.
# If not, delete tag!
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

env:
  NAMESPACE: unbelievable
  COLLECTION_NAME: hpe

jobs:
  check_version:
    name: Verify version tag is OK
    runs-on: ubuntu-latest
    steps:
      - name: Initialize env vars
        uses: briantist/ezenv@v1
        with:
          env: |
            COLLECTION_PATH=ansible_collections/${NAMESPACE}/${COLLECTION_NAME}

      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: ${{ env.COLLECTION_PATH }}
          fetch-depth: 2

      - name: Link to .github # easier access to local actions
        run: ln -s "${COLLECTION_PATH}/.github" .github

      - name: Get version
        uses: ./.github/actions/get-version
        with:
          working-directory: ${{ env.COLLECTION_PATH }}

      - name: Fail if version != tag
        run: |
          TAG=${GITHUB_REF##*/}
          echo "TAG: $TAG"
          [[ ${GITHUB_REF##*/} == "v${VERSION}" ]] || false

      - name: Delete tag
        uses: actions/github-script@v3
        if: ${{ failure() }}
        with:
          github-token: ${{ github.token }}
          script: |
            github.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.ref.replace('refs/', ''),
            })
