---
name: Push to master
on:
  push:
    branches:
      - master
    paths:
      - '**'
      # handled in release workflow
      - '!RELEASE'
  workflow_dispatch:

env:
  NAMESPACE: unbelievable
  COLLECTION_NAME: hpe

jobs:
  check-if-release:
    name: Check if RELEASE is changed
    runs-on: ubuntu-latest
    outputs:
      is-release: ${{ steps.changed-files.outputs.any_changed }}
    steps:
      - name: Initialize env vars
        uses: briantist/ezenv@v1
        with:
          env: |
            COLLECTION_PATH=ansible_collections/${NAMESPACE}/${COLLECTION_NAME}

      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: ${{ env.COLLECTION_PATH }}
          fetch-depth: 2

      - name: Check if RELEASE file changed
        id: changed-files
        uses: tj-actions/changed-files@v11.5
        with:
          path: ${{ env.COLLECTION_PATH }}
          files: |
            RELEASE
  ci:
    name: CI tests
    uses: the-unbelievable-machine/ansible_collection_hpe/.github/workflows/ci.yml@master
    needs: check-if-release
    if: needs.check-if-release.outputs.is-release != 'true'
